# .github/branch-protection-rules.yml

branch_protection_rules:
  - pattern: main # 메인브랜치 (서버동일)
    required_status_checks:
      strict: true
      contexts: ["build", "test"]
    enforce_admins: true
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
    restrictions: null
    require_conversation_resolution: true
    allow_force_pushes: false
    allow_deletions: false

  - pattern: develop # 개발브랜치 (현재미사용용)
    required_status_checks:
      strict: true
      contexts: ["build", "test"]
    enforce_admins: true
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
    restrictions: null
    require_conversation_resolution: true
    allow_force_pushes: false
    allow_deletions: false

  - pattern: feat/* # 개발자별 브랜치치
    required_status_checks: null
    enforce_admins: false
    required_pull_request_reviews:
      dismiss_stale_reviews: false
      required_approving_review_count: 1
    restrictions: null
    require_conversation_resolution: false
    allow_force_pushes: true
    allow_deletions: true

  - pattern: fix/* # 긴급수정사항 (현재미사용)
    required_status_checks: null
    enforce_admins: false
    required_pull_request_reviews:
      dismiss_stale_reviews: false
      required_approving_review_count: 1
    restrictions: null
    require_conversation_resolution: false
    allow_force_pushes: true
    allow_deletions: true
