version: '3.8'

services:
  db:
    image: postgres:15
    container_name: travel-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: travel_agency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./demo/docker/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./demo/docker/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
    networks:
      - travel-net

volumes:
  db-data:

networks:
  travel-net:
