server:
  port: 8083

spring:
  application:
    name: demo

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:init.sql

  datasource:
    url: jdbc:postgresql://localhost:5433/travel_agency
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    user:
      name: test
      password: 1234
      roles: USER,ADMIN

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.travelAgency.model

logging:
  level:
    root: info
    org.springframework.web: debug

file:
  upload-dir: ./uploads
