server:
  port: 8081

spring:
  application:
    name: demo

  sql:
    init:
      mode: always
#      schema-locations: classpath:docker/01_schema.sql // 스프링부트가 자동으로 경로 잡음
#      data-locations: classpath:docker/02_data.sql // 한줄이라도 에러 발생시 이후 라인은 진행 x

  datasource:
    url: jdbc:postgresql://localhost:5433/travel_agency
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    user:
      name: test
      password: 1234
      roles: USER,ADMIN

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: com.example.demo.vo

logging:
  level:
    root: info
    org.springframework.web: debug

file:
  upload-dir: ./uploads
